package com.insurance.thinux.insytespringboot.enums;

public enum District {
    AMPARA, ANURADHAPURA, BADULLA, BATTICALOA, COLOMBO, GALLE, GAMPAHA, HAMBANTOTA, JAFFNA, KALUTARA, KANDY,
    KEGALLE, KILINOCHCHI, KURUNEGALA, MANNAR, MATALE, MATARA, MONERAGALA , MULLAITTIVU, NUWARA_ELIYA, POLONNARUWA,
    PUTTALAM, RATNAPURA, TRINCOMALEE, VAVUNIYA;
    }
